### ISSUE TITLE
Software may cause laxative effects

### ISSUE THREAD

**Issue by ghost** [bs2kbs2k/PasswordChkr#1]
oh god help its everyoewrr oh god oh fuck help

**Comment by bs2kbs2k** [comment]
this is a serious software developed by a serious person

**Comment by ghost** [comment]
> this is a serious software developed by a serious person

ahhhhh ehlp please its EVRRYEHWRRE i mean literally EVERYWHERE its on the WALLS,,

**Comment by bs2kbs2k** [comment]
go see a doctor
